//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Revit.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Entitlement : global::System.Configuration.ApplicationSettingsBase {
        
        private static Entitlement defaultInstance = ((Entitlement)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Entitlement())));
        
        public static Entitlement Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime TimeStamp {
            get {
                return ((global::System.DateTime)(this["TimeStamp"]));
            }
            set {
                this["TimeStamp"] = value;
            }
        }
    }
}
